#!/bin/bash
set -o nounset -o errexit -o pipefail

repository_top="$(git rev-parse --show-toplevel)"
prefix=${PWD##$repository_top/}
cd "$repository_top"
git subtree push --prefix "$prefix" https://github.com/knaka/magefiles-common main
