// Language Guide (proto 3) | Protocol Buffers Documentation https://protobuf.dev/programming-guides/proto3/

// @generated by protoc-gen-es v1.10.0 with parameter "target=js+dts"
// @generated from file v1/main.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.VersionInfo
 */
export declare class VersionInfo extends Message<VersionInfo> {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  constructor(data?: PartialMessage<VersionInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.VersionInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VersionInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VersionInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VersionInfo;

  static equals(a: VersionInfo | PlainMessage<VersionInfo> | undefined, b: VersionInfo | PlainMessage<VersionInfo> | undefined): boolean;
}

/**
 * @generated from message v1.GetVersionInfoRequest
 */
export declare class GetVersionInfoRequest extends Message<GetVersionInfoRequest> {
  constructor(data?: PartialMessage<GetVersionInfoRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetVersionInfoRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetVersionInfoRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetVersionInfoRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetVersionInfoRequest;

  static equals(a: GetVersionInfoRequest | PlainMessage<GetVersionInfoRequest> | undefined, b: GetVersionInfoRequest | PlainMessage<GetVersionInfoRequest> | undefined): boolean;
}

/**
 * @generated from message v1.GetVersionInfoResponse
 */
export declare class GetVersionInfoResponse extends Message<GetVersionInfoResponse> {
  /**
   * @generated from field: v1.VersionInfo version_info = 1;
   */
  versionInfo?: VersionInfo;

  constructor(data?: PartialMessage<GetVersionInfoResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetVersionInfoResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetVersionInfoResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetVersionInfoResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetVersionInfoResponse;

  static equals(a: GetVersionInfoResponse | PlainMessage<GetVersionInfoResponse> | undefined, b: GetVersionInfoResponse | PlainMessage<GetVersionInfoResponse> | undefined): boolean;
}

