// Language Guide (proto 3) | Protocol Buffers Documentation https://protobuf.dev/programming-guides/proto3/

// @generated by protoc-gen-es v1.10.0 with parameter "target=js+dts"
// @generated from file v1/main.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message v1.VersionInfo
 */
export const VersionInfo = /*@__PURE__*/ proto3.makeMessageType(
  "v1.VersionInfo",
  () => [
    { no: 1, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.VersionInfoRequest
 */
export const VersionInfoRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.VersionInfoRequest",
  [],
);

/**
 * @generated from message v1.VersionInfoResponse
 */
export const VersionInfoResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.VersionInfoResponse",
  () => [
    { no: 1, name: "version_info", kind: "message", T: VersionInfo },
  ],
);

/**
 * @generated from message v1.StatusRequest
 */
export const StatusRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.StatusRequest",
  [],
);

/**
 * @generated from message v1.StatusResponse
 */
export const StatusResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.StatusResponse",
  () => [
    { no: 1, name: "InitialScanFinished", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message v1.CurrentTimeRequest
 */
export const CurrentTimeRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.CurrentTimeRequest",
  [],
);

/**
 * @generated from message v1.CurrentTimeResponse
 */
export const CurrentTimeResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.CurrentTimeResponse",
  () => [
    { no: 1, name: "timestamp", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message v1.QueryRequest
 */
export const QueryRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.QueryRequest",
  () => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.QueryResult
 */
export const QueryResult = /*@__PURE__*/ proto3.makeMessageType(
  "v1.QueryResult",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "snippet", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.QueryResponse
 */
export const QueryResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.QueryResponse",
  () => [
    { no: 1, name: "results", kind: "message", T: QueryResult, repeated: true },
  ],
);

/**
 * @generated from message v1.ContentRequest
 */
export const ContentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ContentRequest",
  () => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.ContentResponse
 */
export const ContentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ContentResponse",
  () => [
    { no: 1, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.LaunchPathRequest
 */
export const LaunchPathRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.LaunchPathRequest",
  () => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.LaunchPathResponse
 */
export const LaunchPathResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.LaunchPathResponse",
  [],
);

