// Language Guide (proto 3) | Protocol Buffers Documentation https://protobuf.dev/programming-guides/proto3/

// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=js+dts"
// @generated from file v1/main.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ContentRequest, ContentResponse, CurrentTimeRequest, CurrentTimeResponse, OpenFileRequest, OpenFileResponse, OpenURLRequest, OpenURLResponse, QueryRequest, QueryResponse, StatusRequest, StatusResponse, VersionInfoRequest, VersionInfoResponse } from "./main_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.MainService
 */
export declare const MainService: {
  readonly typeName: "v1.MainService",
  readonly methods: {
    /**
     * @generated from rpc v1.MainService.VersionInfo
     */
    readonly versionInfo: {
      readonly name: "VersionInfo",
      readonly I: typeof VersionInfoRequest,
      readonly O: typeof VersionInfoResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.MainService.Status
     */
    readonly status: {
      readonly name: "Status",
      readonly I: typeof StatusRequest,
      readonly O: typeof StatusResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.MainService.CurrentTime
     */
    readonly currentTime: {
      readonly name: "CurrentTime",
      readonly I: typeof CurrentTimeRequest,
      readonly O: typeof CurrentTimeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.MainService.Query
     */
    readonly query: {
      readonly name: "Query",
      readonly I: typeof QueryRequest,
      readonly O: typeof QueryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.MainService.Content
     */
    readonly content: {
      readonly name: "Content",
      readonly I: typeof ContentRequest,
      readonly O: typeof ContentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.MainService.OpenFile
     */
    readonly openFile: {
      readonly name: "OpenFile",
      readonly I: typeof OpenFileRequest,
      readonly O: typeof OpenFileResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.MainService.OpenURL
     */
    readonly openURL: {
      readonly name: "OpenURL",
      readonly I: typeof OpenURLRequest,
      readonly O: typeof OpenURLResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

