// Language Guide (proto 3) | Protocol Buffers Documentation https://protobuf.dev/programming-guides/proto3/

// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=js+dts"
// @generated from file v1/main.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetVersionInfoRequest, GetVersionInfoResponse } from "./main_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.MainService
 */
export declare const MainService: {
  readonly typeName: "v1.MainService",
  readonly methods: {
    /**
     * @generated from rpc v1.MainService.GetVersionInfo
     */
    readonly getVersionInfo: {
      readonly name: "GetVersionInfo",
      readonly I: typeof GetVersionInfoRequest,
      readonly O: typeof GetVersionInfoResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

