// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcgen

import (
	"time"
)

type File struct {
	Path       string
	FtsFileID  int64
	ModifiedAt time.Time
	Size       int64
	UpdatedAt  time.Time
}

type FtsFile struct {
	Body string
}

type Log struct {
	ID        int64
	Message   string
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Username  string
	Password  string
	CreatedAt time.Time
}
