// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type File struct {
	Path       string
	FtsFileID  int64
	ModifiedAt time.Time
	Size       int64
	UpdatedAt  time.Time
}

type Ft struct {
	B string
}

type FtsFile struct {
	Body string
}

type Log struct {
	ID        int64
	Message   string
	CreatedAt time.Time
}

type Tbl struct {
	A int64
	B sql.NullString
	C sql.NullString
	D sql.NullString
	E sql.NullInt64
}

type TblFt struct {
	B string
	C string
}

type User struct {
	ID        int64
	Username  string
	Password  string
	CreatedAt time.Time
}
